version: "3"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - app-network
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
      - ./pdfs:/usr/src/app/pdfs
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      PDF_DIRECTORY: /usr/src/app/pdfs
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - app-network
volumes:
  db_data: {}
networks:
  app-network:
    driver: bridge
