CREATE DATABASE IF NOT EXISTS pdf_database;

CREATE USER 'myuser'@'%' IDENTIFIED BY '1364508042Leo@!';

GRANT ALL PRIVILEGES ON pdf_database.* TO 'root'@'%';
FLUSH PRIVILEGES;

USE pdf_database;

CREATE TABLE IF NOT EXISTS pdf_info (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pdf_name VARCHAR(255) NOT NULL,
  pdf_path VARCHAR(255) NOT NULL
);